version: "3.9"
services:
  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./.docker/volumes/database:/var/lib/postgresql/data
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/track_investments
    ports:
      - "3000:3000"
    depends_on:
      - database