default: &default
  adapter: postgresql
  encoding: unicode
  host: database
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: track_investments_development

test:
  <<: *default
  database: track_investments_test
#
production:
  <<: *default
  database: track_investments_production

